### ISSUE TITLE
AttributeError: 'SMBus' object has no attribute 'write_bytes'

### ISSUE THREAD

**Issue by berkaysit** [adafruit/Adafruit_CircuitPython_TSL2591#8]
Hi, I wrote the following code in the light of your example tsl2591_simpletest.py. It's working fine. But if I call the method getTSL2591Data() from another Python file, I faced an error: `AttributeError: 'SMBus' object has no attribute 'write_bytes'`

I have Python3 enviroment in RPi 3.

This works fine by self, getTSL2591.py:
```import time
import json
import board
import busio
import adafruit_tsl2591

def getTSL2591Data():
	# Initialize the I2C bus.
	i2c = busio.I2C(board.SCL, board.SDA)

	# Initialize the sensor.
	sensor = adafruit_tsl2591.TSL2591(i2c)
	
	measurementArr = {}
	try:
		# Read the total lux, IR, and visible light levels
		measurementArr = {'lux': round(sensor.lux,2), 'infrared': round(sensor.infrared,2), 'visible': round(sensor.visible,2), 'full_spectrum': round(sensor.full_spectrum,2)}
	except RuntimeError as e:
		print("Reading from TSL2591 failure: ",e.args)
	except NameError:
		print("NameError")
	finally:
		return json.dumps(measurementArr, sort_keys=True)

try:
	if __name__ == "__main__":
		print(getTSL2591Data())
    
except KeyboardInterrupt:
	print("Exit!")
```

The file getTele.py: I call getTSL2591.getTSL2591Data() method in this file 
```
import time
import datetime
import json
import getTSL2591

def getTelemetryData():
	TSL2591Data = json.loads(getTSL2591.getTSL2591Data())

	dateTimeNow = datetime.datetime.now()
	dateTimeNow = dateTimeNow.strftime("%d.%m.%Y %H:%M:%S")
	measurementArr = {}

	measurementArr = {'measuringTime': dateTimeNow, 'lux': TSL2591Data['lux'], 'infrared': TSL2591Data['infrared'], 'visible': TSL2591Data['visible'], 'full_spectrum': TSL2591Data['full_spectrum'] }

	return json.dumps(measurementArr, sort_keys=True)

try:
    if __name__ == "__main__":
        time.sleep(1)
        print(getTelemetryData())
    
except KeyboardInterrupt:
    print("Exit!")


```

And then, the following error occurs:

```
Traceback (most recent call last):
  File "getTele.py", line 20, in <module>
    print(getTelemetryData())
  File "getTele.py", line 7, in getTelemetryData
    TSL2591Data = json.loads(getTSL2591.getTSL2591Data())
  File "/var/www/html/python/getTSL2591.py", line 12, in getTSL2591Data
    sensor = adafruit_tsl2591.TSL2591(i2c)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_circuitpython_tsl2591-1.1.1.dev8+g8a9647b-py3.5.egg/adafruit_tsl2591.py", line 113, in __init__
  File "/usr/local/lib/python3.5/dist-packages/adafruit_circuitpython_busdevice-2.2.5-py3.5.egg/adafruit_bus_device/i2c_device.py", line 64, in __init__
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_Blinka-0.2.3-py3.5.egg/busio.py", line 63, in writeto
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_Blinka-0.2.3-py3.5.egg/adafruit_blinka/microcontroller/raspi_23/i2c.py", line 38, in writeto
AttributeError: 'SMBus' object has no attribute 'write_bytes'
```

**Comment by berkaysit** [comment]
I realized something; if I run the command with sudo like `sudo python3 tsl2591_simpletest.py` I encounter the error I mentioned above. But it can run without sudo. So, why?

**Comment by ladyada** [comment]
maybe you have different python libraries installed for root or user 'pi'?

**Comment by berkaysit** [comment]
I installed the libraries Adafruit_Blinka, Adafruit_CircuitPython_BusDevice, Adafruit_CircuitPython_TSL2591 and I made installation like below for each library: 
```
git clone https://github.com/adafruit/Adafruit_CircuitPython_TSL2591.git
cd Adafruit_CircuitPython_TSL2591
sudo python3 setup.py install
```

I did not choose any virtual environment. But could you please suggest how to check it? Or do you suggest any other installation method please?

**Comment by ladyada** [comment]
oh dont do that, use pip3
https://learn.adafruit.com/tsl2561/python-circuitpython
follow these instructions, you'll want to uninstall it from the way you did it above

**Comment by berkaysit** [comment]
Thank you for your answer. I uninstall my previous installed libraries, and then installed the following;

`sudo pip3 install adafruit-blinka`
`sudo pip3 install Adafruit_CircuitPython_TSL2591`

But I still can run `python3 example/tsl2591_simpletest.py`without sudo, but with sudo I encountered the same following error:

```
sudo python3 tsl2591_simpletest.py 

Traceback (most recent call last):
  File "tsl2591_simpletest.py", line 14, in <module>
    sensor = adafruit_tsl2591.TSL2591(i2c)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_tsl2591.py", line 111, in __init__
    self._device = i2c_device.I2CDevice(i2c, address)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_bus_device/i2c_device.py", line 64, in __init__
    i2c.writeto(device_address, b'')
  File "/usr/local/lib/python3.5/dist-packages/busio.py", line 63, in writeto
    return self._i2c.writeto(address, buffer, stop=stop)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/raspi_23/i2c.py", line 38, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
AttributeError: 'SMBus' object has no attribute 'write_bytes'

```

**Comment by ladyada** [comment]
maybe try 'sudo pip3 install --upgrade adafruit-blinka'
and also 'sudo pip3 install --upgrade  Adafruit-GPIO' and 'sudo pip3 install --upgrade  Adafruit-PureIO`

**Comment by kattni** [comment]
@berkaysit Hello! Are you still experiencing this issue? Let us know so we can help you out or close this issue. Thanks!

**Comment by ladyada** [comment]
closing due to lack of activity
